URL=jdbc:mysql://localhost:3306/personal_trainer_digitale

LOGIN_USER = loginUser
LOGIN_PASSWORD = login
ATLETA_USER = atletaUser
ATLETA_PASSWORD = atleta
PERSONAL_USER = personalUser
PERSONAL_PASSWORD = personal
GESTORE_USER = gestoreUser
GESTORE_PASSWORD = gestore